<?php
echo "<!DOCTYPE HTML>\n"; 
echo "<!--\n"; 
echo "	Dimension by HTML5 UP\n"; 
echo "	html5up.net | @ajlkn\n"; 
echo "	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)\n"; 
echo "-->\n"; 
echo "<html>\n"; 
echo "	<head>\n"; 
echo "		<title>Rohan Dighe</title>\n"; 
echo "		<meta charset=\"utf-8\" />\n"; 
echo "		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\n"; 
echo "		<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\n"; 
echo "		<!--[if lte IE 9]><link rel=\"stylesheet\" href=\"assets/css/ie9.css\" /><![endif]-->\n"; 
echo "		<noscript><link rel=\"stylesheet\" href=\"assets/css/noscript.css\" /></noscript>\n"; 
echo "        <link rel=\"icon\" href=\"images/thumbnail.png\">\n"; 
echo "        \n"; 
echo "        <script>\n"; 
echo "            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n"; 
echo "            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n"; 
echo "            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n"; 
echo "            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');\n"; 
echo "\n"; 
echo "            ga('create', 'UA-101209365-1', 'auto');\n"; 
echo "            ga('send', 'pageview');\n"; 
echo "\n"; 
echo "        </script>\n"; 
echo "    </head>\n"; 
echo "    \n"; 
echo "	<body>\n"; 
echo "\n"; 
echo "		<!-- Wrapper -->\n"; 
echo "			<div id=\"wrapper\">\n"; 
echo "\n"; 
echo "				<!-- Header -->\n"; 
echo "					<header id=\"header\">\n"; 
echo "						<div class=\"logo\">\n"; 
echo "							<span class=\"icon fa-flask\"></span>\n"; 
echo "						</div>\n"; 
echo "						<div class=\"content\">\n"; 
echo "							<div class=\"inner\">\n"; 
echo "								<h1>Rohan Dighe</h1>\n"; 
echo "								<p><!--[-->Student at Purdue University's Honors College, <!--]--><br />\n"; 
echo "								<!--[-->Honors First Year Engineering Program and Davidson School<!--]--><br/>\n"; 
echo "                                <!--[-->of Chemical Engineering<!--]--></p>\n"; 
echo "							</div>\n"; 
echo "						</div>\n"; 
echo "						<nav>\n"; 
echo "							<ul>\n"; 
echo "								<li><a href=\"#intro\">Intro</a></li>\n"; 
echo "								<!--<li><a href=\"#work\">Work</a></li>-->\n"; 
echo "								<li><a href=\"#about\">About</a></li>\n"; 
echo "								<li><a href=\"#contact\">Contact</a></li>\n"; 
echo "								<!--<li><a href=\"#elements\">Elements</a></li>-->\n"; 
echo "							</ul>\n"; 
echo "						</nav>\n"; 
echo "					</header>\n"; 
echo "\n"; 
echo "				<!-- Main -->\n"; 
echo "					<div id=\"main\">\n"; 
echo "\n"; 
echo "						<!-- Intro -->\n"; 
echo "							<article id=\"intro\">\n"; 
echo "								<h2 class=\"major\">Intro</h2>\n"; 
echo "								<!--<span class=\"image main\"><img src=\"images/fountain.jpg\" alt=\"\" /></span>-->\n"; 
echo "								<p>Currently enrolled in the Honors First Year Engineering program with an intended major in Chemical Engineering, I am a driven and motivated person deeply involved in on-campus activities ranging from Honors Engineering Leadership Council to the Purdue chapter of the American Institute of Chemical Engineers, as well as various academic enterprises such as research and Honors coursework.</p>\n"; 
echo "								\n"; 
echo "                                </article>\n"; 
echo "\n"; 
echo "						\n"; 
echo "\n"; 
echo "						<!-- About -->\n"; 
echo "							<article id=\"about\">\n"; 
echo "								<h2 class=\"major\">About</h2>\n"; 
echo "								\n"; 
echo "                                <ul class = \"actions\"><li><a href=\"Rohan Dighe Resume.pdf\" class=\"button special\">My Resum&Eacute; - Updated 6/17/2017</a></li></ul>\n"; 
echo "                                <p>Through intensive coursework and extracurricular activities, I have developed and exhibited strengths in several key technical and non-technical skill areas.</p>\n"; 
echo "                                <p><strong>Technical Skills:</strong><br />\n"; 
echo "                                <i>Algorithmic Problem Solving</i> as evidenced by proficiency in several programming languages including MATLAB, Python, and C as well as skills such as flowcharting and other forms of visual modeling.<br />\n"; 
echo "                                <span class=\"image main\"><img src=\"images/proj3.jpg\" alt=\"\" /></span>\n"; 
echo "                                <i>Physical and Mathematical Modeling</i> as evidenced by the ability to build and program two different functioning prototype robots using two different programming languages as well as the ability to create a mathematical model to predict and optimize hydro energy storage system cost and efficiency.<br />\n"; 
echo "                               \n"; 
echo "                                <span class=\"image main\"><img src=\"images/proj2_1.jpg\" alt=\"\" /></span>\n"; 
echo "                                <i>Fundamental Scientific Principles</i> as evidenced by advanced and honors coursework in key scientific areas including chemistry.</p>\n"; 
echo "                                <p><strong>Non-Technical Skills:</strong><br />\n"; 
echo "                                <i>Interpersonal Communication</i> developed through significant roles in the Engineering Honors Learning Community, the Purdue chapter of the American Institute of Chemical Engineers, and the Honors College Ambassadors program.<br /><br />\n"; 
echo "                                <i>Team-Oriented Performance</i> developed through several intensive projects, engineering-related and otherwise, with timelines that range from one week to an entire semester.<br /><br />\n"; 
echo "                                <i>Goal-Oriented Leadership</i> developed through several leadership roles in the Honors Engineering Leadership Council, Purdue AIChE, and the Purdue Society of Professional Engineers.</p>\n"; 
echo "                                \n"; 
echo "								</article>\n"; 
echo "\n"; 
echo "						<!-- Contact -->\n"; 
echo "							<article id=\"contact\">\n"; 
echo "								<h2 class=\"major\">Contact</h2>\n"; 
echo "								<!--<form method=\"post\" action=\"#\">\n"; 
echo "									<div class=\"field half first\">\n"; 
echo "										<label for=\"name\">Name</label>\n"; 
echo "										<input type=\"text\" name=\"name\" id=\"name\" />\n"; 
echo "									</div>\n"; 
echo "									<div class=\"field half\">\n"; 
echo "										<label for=\"email\">Email</label>\n"; 
echo "										<input type=\"text\" name=\"email\" id=\"email\" />\n"; 
echo "									</div>\n"; 
echo "									<div class=\"field\">\n"; 
echo "										<label for=\"message\">Message</label>\n"; 
echo "										<textarea name=\"message\" id=\"message\" rows=\"4\"></textarea>\n"; 
echo "									</div>\n"; 
echo "									<ul class=\"actions\">\n"; 
echo "										<li><input type=\"submit\" value=\"Send Message\" class=\"special\" /></li>\n"; 
echo "										<li><input type=\"reset\" value=\"Reset\" /></li>\n"; 
echo "									</ul>\n"; 
echo "								</form>-->\n"; 
echo "                                \n"; 
echo "								<ul class=\"icons\">\n"; 
echo "									<li><a href=\"mailto:rdighe@purdue.edu\" class=\"icon fa-envelope-o\"><span class=\"label\">Email</span></a></li>\n"; 
echo "									<li><a href=\"https://linkedin.com/in/rdighe1\" class=\"icon fa-linkedin\"><span class=\"label\">LinkedIn</span></a></li>\n"; 
echo "                                    <li><a href=\"#\" class=\"icon fa-facebook\"><span class=\"label\">Facebook</span></a></li>\n"; 
echo "								</ul>\n"; 
echo "                                <!--<span class=\"image main\"><img src=\"images/self.jpg\" alt=\"\" /></span>-->\n"; 
echo "							</article>\n"; 
echo "\n"; 
echo "						<!-- Elements-->\n"; 
echo "							<article id=\"elements\">\n"; 
echo "								<h2 class=\"major\">Elements</h2>\n"; 
echo "\n"; 
echo "								<section>\n"; 
echo "									<h3 class=\"major\">Text</h3>\n"; 
echo "									<p>This is <b>bold</b> and this is <strong>strong</strong>. This is <i>italic</i> and this is <em>emphasized</em>.\n"; 
echo "									This is <sup>superscript</sup> text and this is <sub>subscript</sub> text.\n"; 
echo "									This is <u>underlined</u> and this is code: <code>for (;;) { ... }</code>. Finally, <a href=\"#\">this is a link</a>.</p>\n"; 
echo "									<hr />\n"; 
echo "									<h2>Heading Level 2</h2>\n"; 
echo "									<h3>Heading Level 3</h3>\n"; 
echo "									<h4>Heading Level 4</h4>\n"; 
echo "									<h5>Heading Level 5</h5>\n"; 
echo "									<h6>Heading Level 6</h6>\n"; 
echo "									<hr />\n"; 
echo "									<h4>Blockquote</h4>\n"; 
echo "									<blockquote>Fringilla nisl. Donec accumsan interdum nisi, quis tincidunt felis sagittis eget tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan faucibus. Vestibulum ante ipsum primis in faucibus lorem ipsum dolor sit amet nullam adipiscing eu felis.</blockquote>\n"; 
echo "									<h4>Preformatted</h4>\n"; 
echo "									<pre><code>i = 0;\n"; 
echo "\n"; 
echo "while (!deck.isInOrder()) {\n"; 
echo "    print 'Iteration ' + i;\n"; 
echo "    deck.shuffle();\n"; 
echo "    i++;\n"; 
echo "}\n"; 
echo "\n"; 
echo "print 'It took ' + i + ' iterations to sort the deck.';</code></pre>\n"; 
echo "								</section>\n"; 
echo "\n"; 
echo "								<section>\n"; 
echo "									<h3 class=\"major\">Lists</h3>\n"; 
echo "\n"; 
echo "									<h4>Unordered</h4>\n"; 
echo "									<ul>\n"; 
echo "										<li>Dolor pulvinar etiam.</li>\n"; 
echo "										<li>Sagittis adipiscing.</li>\n"; 
echo "										<li>Felis enim feugiat.</li>\n"; 
echo "									</ul>\n"; 
echo "\n"; 
echo "									<h4>Alternate</h4>\n"; 
echo "									<ul class=\"alt\">\n"; 
echo "										<li>Dolor pulvinar etiam.</li>\n"; 
echo "										<li>Sagittis adipiscing.</li>\n"; 
echo "										<li>Felis enim feugiat.</li>\n"; 
echo "									</ul>\n"; 
echo "\n"; 
echo "									<h4>Ordered</h4>\n"; 
echo "									<ol>\n"; 
echo "										<li>Dolor pulvinar etiam.</li>\n"; 
echo "										<li>Etiam vel felis viverra.</li>\n"; 
echo "										<li>Felis enim feugiat.</li>\n"; 
echo "										<li>Dolor pulvinar etiam.</li>\n"; 
echo "										<li>Etiam vel felis lorem.</li>\n"; 
echo "										<li>Felis enim et feugiat.</li>\n"; 
echo "									</ol>\n"; 
echo "									<h4>Icons</h4>\n"; 
echo "									<ul class=\"icons\">\n"; 
echo "										<li><a href=\"#\" class=\"icon fa-twitter\"><span class=\"label\">Twitter</span></a></li>\n"; 
echo "										<li><a href=\"#\" class=\"icon fa-facebook\"><span class=\"label\">Facebook</span></a></li>\n"; 
echo "										<li><a href=\"#\" class=\"icon fa-instagram\"><span class=\"label\">Instagram</span></a></li>\n"; 
echo "										<li><a href=\"#\" class=\"icon fa-github\"><span class=\"label\">Github</span></a></li>\n"; 
echo "									</ul>\n"; 
echo "\n"; 
echo "									<h4>Actions</h4>\n"; 
echo "									<ul class=\"actions\">\n"; 
echo "										<li><a href=\"#\" class=\"button special\">Default</a></li>\n"; 
echo "										<li><a href=\"#\" class=\"button\">Default</a></li>\n"; 
echo "									</ul>\n"; 
echo "									<ul class=\"actions vertical\">\n"; 
echo "										<li><a href=\"#\" class=\"button special\">Default</a></li>\n"; 
echo "										<li><a href=\"#\" class=\"button\">Default</a></li>\n"; 
echo "									</ul>\n"; 
echo "								</section>\n"; 
echo "\n"; 
echo "								<section>\n"; 
echo "									<h3 class=\"major\">Table</h3>\n"; 
echo "									<h4>Default</h4>\n"; 
echo "									<div class=\"table-wrapper\">\n"; 
echo "										<table>\n"; 
echo "											<thead>\n"; 
echo "												<tr>\n"; 
echo "													<th>Name</th>\n"; 
echo "													<th>Description</th>\n"; 
echo "													<th>Price</th>\n"; 
echo "												</tr>\n"; 
echo "											</thead>\n"; 
echo "											<tbody>\n"; 
echo "												<tr>\n"; 
echo "													<td>Item One</td>\n"; 
echo "													<td>Ante turpis integer aliquet porttitor.</td>\n"; 
echo "													<td>29.99</td>\n"; 
echo "												</tr>\n"; 
echo "												<tr>\n"; 
echo "													<td>Item Two</td>\n"; 
echo "													<td>Vis ac commodo adipiscing arcu aliquet.</td>\n"; 
echo "													<td>19.99</td>\n"; 
echo "												</tr>\n"; 
echo "												<tr>\n"; 
echo "													<td>Item Three</td>\n"; 
echo "													<td> Morbi faucibus arcu accumsan lorem.</td>\n"; 
echo "													<td>29.99</td>\n"; 
echo "												</tr>\n"; 
echo "												<tr>\n"; 
echo "													<td>Item Four</td>\n"; 
echo "													<td>Vitae integer tempus condimentum.</td>\n"; 
echo "													<td>19.99</td>\n"; 
echo "												</tr>\n"; 
echo "												<tr>\n"; 
echo "													<td>Item Five</td>\n"; 
echo "													<td>Ante turpis integer aliquet porttitor.</td>\n"; 
echo "													<td>29.99</td>\n"; 
echo "												</tr>\n"; 
echo "											</tbody>\n"; 
echo "											<tfoot>\n"; 
echo "												<tr>\n"; 
echo "													<td colspan=\"2\"></td>\n"; 
echo "													<td>100.00</td>\n"; 
echo "												</tr>\n"; 
echo "											</tfoot>\n"; 
echo "										</table>\n"; 
echo "									</div>\n"; 
echo "\n"; 
echo "									<h4>Alternate</h4>\n"; 
echo "									<div class=\"table-wrapper\">\n"; 
echo "										<table class=\"alt\">\n"; 
echo "											<thead>\n"; 
echo "												<tr>\n"; 
echo "													<th>Name</th>\n"; 
echo "													<th>Description</th>\n"; 
echo "													<th>Price</th>\n"; 
echo "												</tr>\n"; 
echo "											</thead>\n"; 
echo "											<tbody>\n"; 
echo "												<tr>\n"; 
echo "													<td>Item One</td>\n"; 
echo "													<td>Ante turpis integer aliquet porttitor.</td>\n"; 
echo "													<td>29.99</td>\n"; 
echo "												</tr>\n"; 
echo "												<tr>\n"; 
echo "													<td>Item Two</td>\n"; 
echo "													<td>Vis ac commodo adipiscing arcu aliquet.</td>\n"; 
echo "													<td>19.99</td>\n"; 
echo "												</tr>\n"; 
echo "												<tr>\n"; 
echo "													<td>Item Three</td>\n"; 
echo "													<td> Morbi faucibus arcu accumsan lorem.</td>\n"; 
echo "													<td>29.99</td>\n"; 
echo "												</tr>\n"; 
echo "												<tr>\n"; 
echo "													<td>Item Four</td>\n"; 
echo "													<td>Vitae integer tempus condimentum.</td>\n"; 
echo "													<td>19.99</td>\n"; 
echo "												</tr>\n"; 
echo "												<tr>\n"; 
echo "													<td>Item Five</td>\n"; 
echo "													<td>Ante turpis integer aliquet porttitor.</td>\n"; 
echo "													<td>29.99</td>\n"; 
echo "												</tr>\n"; 
echo "											</tbody>\n"; 
echo "											<tfoot>\n"; 
echo "												<tr>\n"; 
echo "													<td colspan=\"2\"></td>\n"; 
echo "													<td>100.00</td>\n"; 
echo "												</tr>\n"; 
echo "											</tfoot>\n"; 
echo "										</table>\n"; 
echo "									</div>\n"; 
echo "								</section>\n"; 
echo "\n"; 
echo "								<section>\n"; 
echo "									<h3 class=\"major\">Buttons</h3>\n"; 
echo "									<ul class=\"actions\">\n"; 
echo "										<li><a href=\"#\" class=\"button special\">Special</a></li>\n"; 
echo "										<li><a href=\"#\" class=\"button\">Default</a></li>\n"; 
echo "									</ul>\n"; 
echo "									<ul class=\"actions\">\n"; 
echo "										<li><a href=\"#\" class=\"button\">Default</a></li>\n"; 
echo "										<li><a href=\"#\" class=\"button small\">Small</a></li>\n"; 
echo "									</ul>\n"; 
echo "									<ul class=\"actions\">\n"; 
echo "										<li><a href=\"#\" class=\"button special icon fa-download\">Icon</a></li>\n"; 
echo "										<li><a href=\"#\" class=\"button icon fa-download\">Icon</a></li>\n"; 
echo "									</ul>\n"; 
echo "									<ul class=\"actions\">\n"; 
echo "										<li><span class=\"button special disabled\">Disabled</span></li>\n"; 
echo "										<li><span class=\"button disabled\">Disabled</span></li>\n"; 
echo "									</ul>\n"; 
echo "								</section>\n"; 
echo "\n"; 
echo "								<section>\n"; 
echo "									<h3 class=\"major\">Form</h3>\n"; 
echo "									<form method=\"post\" action=\"#\">\n"; 
echo "										<div class=\"field half first\">\n"; 
echo "											<label for=\"demo-name\">Name</label>\n"; 
echo "											<input type=\"text\" name=\"demo-name\" id=\"demo-name\" value=\"\" placeholder=\"Jane Doe\" />\n"; 
echo "										</div>\n"; 
echo "										<div class=\"field half\">\n"; 
echo "											<label for=\"demo-email\">Email</label>\n"; 
echo "											<input type=\"email\" name=\"demo-email\" id=\"demo-email\" value=\"\" placeholder=\"jane@untitled.tld\" />\n"; 
echo "										</div>\n"; 
echo "										<div class=\"field\">\n"; 
echo "											<label for=\"demo-category\">Category</label>\n"; 
echo "											<div class=\"select-wrapper\">\n"; 
echo "												<select name=\"demo-category\" id=\"demo-category\">\n"; 
echo "													<option value=\"\">-</option>\n"; 
echo "													<option value=\"1\">Manufacturing</option>\n"; 
echo "													<option value=\"1\">Shipping</option>\n"; 
echo "													<option value=\"1\">Administration</option>\n"; 
echo "													<option value=\"1\">Human Resources</option>\n"; 
echo "												</select>\n"; 
echo "											</div>\n"; 
echo "										</div>\n"; 
echo "										<div class=\"field half first\">\n"; 
echo "											<input type=\"radio\" id=\"demo-priority-low\" name=\"demo-priority\" checked>\n"; 
echo "											<label for=\"demo-priority-low\">Low</label>\n"; 
echo "										</div>\n"; 
echo "										<div class=\"field half\">\n"; 
echo "											<input type=\"radio\" id=\"demo-priority-high\" name=\"demo-priority\">\n"; 
echo "											<label for=\"demo-priority-high\">High</label>\n"; 
echo "										</div>\n"; 
echo "										<div class=\"field half first\">\n"; 
echo "											<input type=\"checkbox\" id=\"demo-copy\" name=\"demo-copy\">\n"; 
echo "											<label for=\"demo-copy\">Email me a copy</label>\n"; 
echo "										</div>\n"; 
echo "										<div class=\"field half\">\n"; 
echo "											<input type=\"checkbox\" id=\"demo-human\" name=\"demo-human\" checked>\n"; 
echo "											<label for=\"demo-human\">Not a robot</label>\n"; 
echo "										</div>\n"; 
echo "										<div class=\"field\">\n"; 
echo "											<label for=\"demo-message\">Message</label>\n"; 
echo "											<textarea name=\"demo-message\" id=\"demo-message\" placeholder=\"Enter your message\" rows=\"6\"></textarea>\n"; 
echo "										</div>\n"; 
echo "										<ul class=\"actions\">\n"; 
echo "											<li><input type=\"submit\" value=\"Send Message\" class=\"special\" /></li>\n"; 
echo "											<li><input type=\"reset\" value=\"Reset\" /></li>\n"; 
echo "										</ul>\n"; 
echo "									</form>\n"; 
echo "								</section>\n"; 
echo "\n"; 
echo "							</article>\n"; 
echo "\n"; 
echo "					</div>\n"; 
echo "\n"; 
echo "				<!-- Footer -->\n"; 
echo "					<footer id=\"footer\">\n"; 
echo "						<p class=\"copyright\">&copy; Rohan Dighe, 2017</p>\n"; 
echo "					</footer>\n"; 
echo "\n"; 
echo "			</div>\n"; 
echo "\n"; 
echo "		<!-- BG -->\n"; 
echo "			<div id=\"bg\"></div>\n"; 
echo "\n"; 
echo "		<!-- Scripts -->\n"; 
echo "			<script src=\"assets/js/jquery.min.js\"></script>\n"; 
echo "			<script src=\"assets/js/skel.min.js\"></script>\n"; 
echo "			<script src=\"assets/js/util.js\"></script>\n"; 
echo "			<script src=\"assets/js/main.js\"></script>\n"; 
echo "\n"; 
echo "	</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>